In [42]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.naive_bayes import GaussianNB

In [18]:
data = {
    "City Population": [
        13515000, 13515000, 12478447, 12478447, 27500000, 27500000, 2187526, 21515000, 3076047, 9120350,
        14500000, 9800000, 4500000, 7600000, 3200000, 18700000, 5300000, 10200000, 1600000, 8900000,
        15000000, 2200000, 3300000, 3400000, 25000000, 17500000, 9500000, 13800000, 4700000, 2650000,
        15500000, 3300000, 29000000, 18500000, 17800000, 4100000, 6800000, 9900000, 25500000, 12200000
    ],
    
    "Continent": [
        "North America", "North America", "North America", "Europe", "Europe", "North America", "Europe",
        "India", "North America", "North America",
        "North America", "India", "North America", "India", "North America", "North America", "Europe",
        "Europe", "North America", "India",
        "Europe", "North America", "India", "India", "India", "India",
        "India", "North America", "India", "North America",
        "India", "North America", "India", "Europe", "North America", "North America",
        "Europe", "North America", "Europe", "India"
    ],
    
    "Venue Capacity": [
        8000, 8000, 15000, 15000, 11000, 11000, 14900, 12300, 22800, 33200,
        9000, 12000, 5600, 8700, 4400, 26000, 15000, 18000, 4700, 21000,
        19000, 5400, 6200, 7100, 32000, 25000, 14000, 27000, 9000, 5300,
        20000, 7500, 35000, 22000, 19500, 6800, 9300, 16000, 30000, 14000
    ],
    
    "Day of Week": [
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
        "Monday", "Tuesday", "Wednesday",
        "Thursday", "Friday", "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday",
        "Thursday", "Friday", "Saturday",
        "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
        "Saturday", "Sunday", "Monday", "Tuesday",
        "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "Monday",
        "Tuesday", "Wednesday", "Thursday", "Friday"
    ],

    "Multiple Concerts": [
        1,1,1,1,1,1,0,0,0,0,
        1,0,1,0,1,0,1,1,0,1,
        0,1,0,1,1,0,0,1,0,0,
        1,1,0,0,1,0,0,1,1,1
    ],

    "Sold Out": [
        0,1,1,0,1,1,1,1,0,1,
        0,1,0,1,1,0,1,1,0,1,
        1,0,1,0,1,1,0,1,0,1,
        1,1,0,0,1,0,1,0,1,1
    ]
}
df = pd.DataFrame(data)
df.head()

,City Population,Continent,Venue Capacity,Day of Week,Multiple Concerts,Sold Out
0,13515000,North America,8000,Monday,1,0
1,13515000,North America,8000,Tuesday,1,1
2,12478447,North America,15000,Wednesday,1,1
3,12478447,Europe,15000,Thursday,1,0
4,27500000,Europe,11000,Friday,1,1

In [19]:
ohe = OneHotEncoder(handle_unknown = 'ignore', sparse_output=False).set_output(transform='pandas')
df2 = ohe.fit_transform(df[['Continent', 'Day of Week']])

In [26]:
df2.head()

,Continent_Europe,Continent_India,Continent_North America,Day of Week_Friday,Day of Week_Monday,Day of Week_Saturday,Day of Week_Sunday,Day of Week_Thursday,Day of Week_Tuesday,Day of Week_Wednesday
0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df = pd.concat([df,df2], axis=1)
df.head()

,City Population,Continent,Venue Capacity,Day of Week,Multiple Concerts,Sold Out,Continent_Europe,Continent_India,Continent_North America,Day of Week_Friday,...,Continent_Europe,Continent_India,Continent_North America,Day of Week_Friday,Day of Week_Monday,Day of Week_Saturday,Day of Week_Sunday,Day of Week_Thursday,Day of Week_Tuesday,Day of Week_Wednesday
0,13515000,North America,8000,Monday,1,0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,13515000,North America,8000,Tuesday,1,1,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,12478447,North America,15000,Wednesday,1,1,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,12478447,Europe,15000,Thursday,1,0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,27500000,Europe,11000,Friday,1,1,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
remove_col = ['Conrinent']
df = df.drop(columns = df[['Continent', 'Day of Week']])

In [32]:
X = df.drop(columns='Sold Out')
y = df['Sold Out']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=11, test_size=0.2)

In [34]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [40]:
model.score(X_train, y_train)

0.65625

In [41]:
model.score(X_test, y_test)

0.5

# Hyprparameter Tunning

In [46]:
param_grid = {
    'var_smoothing': [0.00000001, 0.0000001, 0.00000001]
}

In [47]:
grid_search = GridSearchCV(model, param_grid = param_grid, scoring='accuracy', cv=5,n_jobs=-1)

In [48]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': [1e-08, 1e-07, 1e-08]},
             scoring='accuracy')

In [51]:
grid_search.best_params_

{'var_smoothing': 1e-08}

In [52]:
grid_search.best_score_

np.float64(0.5047619047619047)