In [1]:
import pandas as pd
import numpy as np

In [3]:
miles = pd.DataFrame({"farthest_run_mi":[50,60,np.nan,100,26,13,31,50]})

In [6]:
miles

   farthest_run_mi
0             50.0
1             60.0
2              NaN
3            100.0
4             26.0
5             13.0
6             31.0
7             50.0

In [7]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [8]:
from sklearn.impute import SimpleImputer

In [9]:
imp_mean = SimpleImputer(strategy="mean")

In [11]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 60.        ],
       [ 47.14285714],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

In [13]:
imp_median = SimpleImputer(strategy="median")

In [15]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 60.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [18]:
imp_mode = SimpleImputer(strategy='most_frequent')

In [19]:
imp_mode.fit_transform(miles)

array([[ 50.],
       [ 60.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [21]:
imp_constant = SimpleImputer(strategy='constant', fill_value = 15)

In [22]:
imp_constant.fit_transform(miles)

array([[ 50.],
       [ 60.],
       [ 15.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [23]:
names = pd.DataFrame({"Name": ['kavin', 'manvendra', 'vansh',np.nan, 'dhaivat']})

In [24]:
imp_const_cat = SimpleImputer(strategy='constant', fill_value="Unknown")

In [25]:
imp_const_cat.fit_transform(names)

array([['kavin'],
       ['manvendra'],
       ['vansh'],
       ['Unknown'],
       ['dhaivat']], dtype=object)

In [26]:
data = {
    'Name': ['Ryan', 'Nolan', 'Walter', 'Honus', 'Christy', np.nan, 'Napoleon', 'Tris'],
    'farthest_run_mi': [50.0, 62.0, np.nan, 100.0, 26.0, 13.0, 31.0, 50.0]
}

simple_imputer = pd.DataFrame(data)

In [28]:
simple_imputer.head(10)

       Name  farthest_run_mi
0      Ryan             50.0
1     Nolan             62.0
2    Walter              NaN
3     Honus            100.0
4   Christy             26.0
5       NaN             13.0
6  Napoleon             31.0
7      Tris             50.0

In [29]:
from sklearn.compose import make_column_transformer

In [33]:
ct = make_column_transformer(
    (imp_const_cat,['Name']),
    (imp_mean,['farthest_run_mi']),
    remainder = 'drop'
)

In [34]:
ct.set_output(transform='pandas')

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='Unknown',
                                               strategy='constant'),
                                 ['Name']),
                                ('simpleimputer-2', SimpleImputer(),
                                 ['farthest_run_mi'])])

In [37]:
df_pandas = ct.fit_transform(simple_imputer)

In [38]:
df_pandas

  simpleimputer-1__Name  simpleimputer-2__farthest_run_mi
0                  Ryan                         50.000000
1                 Nolan                         62.000000
2                Walter                         47.428571
3                 Honus                        100.000000
4               Christy                         26.000000
5               Unknown                         13.000000
6              Napoleon                         31.000000
7                  Tris                         50.000000