# One Hot Encoder

### This encoder is used to convert categorical data into numeric data

In [1]:
import pandas as pd

In [2]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [3]:
df = pd.DataFrame(data=d)

In [10]:
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [6]:
df.shape

(12, 3)

In [12]:
df.describe()

              sales
count  1.200000e+01
mean   3.736203e+05
std    4.228887e+05
min    1.000000e+04
25%    8.625000e+04
50%    1.665555e+05
75%    6.415000e+05
max    1.111111e+06

In [13]:
df["city"].unique()

array(['Tampa', 'Orlando', 'Jacksonville', 'Miami'], dtype=object)

In [1]:
from sklearn.preprocessing import OneHotEncoder

In [2]:
ohe = OneHotEncoder(handle_unknown = 'ignore', sparse_output=False).set_output(transform='pandas')

In [3]:
ohetransform = ohe.fit_transform(df[["city"]])

NameError: name 'df' is not defined

In [23]:
ohetransform

    city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                 0.0         0.0           0.0         1.0
1                 0.0         0.0           0.0         1.0
2                 0.0         0.0           1.0         0.0
3                 1.0         0.0           0.0         0.0
4                 0.0         1.0           0.0         0.0
5                 1.0         0.0           0.0         0.0
6                 0.0         1.0           0.0         0.0
7                 0.0         1.0           0.0         0.0
8                 0.0         0.0           1.0         0.0
9                 0.0         0.0           1.0         0.0
10                0.0         0.0           1.0         0.0
11                0.0         0.0           1.0         0.0

In [25]:
df = pd.concat([df, ohetransform], axis=1).drop(columns=['city'])

In [28]:
df.head(10)

     sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0   100000   Small                0.0         0.0           0.0         1.0
1   222000  Medium                0.0         0.0           0.0         1.0
2  1000000   Large                0.0         0.0           1.0         0.0
3   522000   Large                1.0         0.0           0.0         0.0
4   111111   Small                0.0         1.0           0.0         0.0
5   222222  Medium                1.0         0.0           0.0         0.0
6  1111111   Large                0.0         1.0           0.0         0.0
7    20000   Small                0.0         1.0           0.0         0.0
8    75000  Medium                0.0         0.0           1.0         0.0
9    90000  Medium                0.0         0.0           1.0         0.0